//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18046
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donor {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DonorAppW8.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абсолютные противопоказания.
        /// </summary>
        public static string AbsContras {
            get {
                return ResourceManager.GetString("AbsContras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на аккаунт.
        /// </summary>
        public static string AccountHeader {
            get {
                return ResourceManager.GetString("AccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на достижения.
        /// </summary>
        public static string Achieves {
            get {
                return ResourceManager.GetString("Achieves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Достижения.
        /// </summary>
        public static string AchievesMenu {
            get {
                return ResourceManager.GetString("AchievesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запланировать.
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить отзыв.
        /// </summary>
        public static string AddReview {
            get {
                return ResourceManager.GetString("AddReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объявления.
        /// </summary>
        public static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объявления.
        /// </summary>
        public static string AdsTitle {
            get {
                return ResourceManager.GetString("AdsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на После сдачи крови.
        /// </summary>
        public static string AfterBloodDonation {
            get {
                return ResourceManager.GetString("AfterBloodDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • 10–15 минут посидите спокойно и, если вы хорошо себя чувствуете (не испытываете слабости или головокружения), пройдите в буфет и выпейте сладкий чай.&lt;br/&gt;
        ///• Если вы почувствовали головокружение, обратитесь к медперсоналу. Самый простой способ помочь себе – лечь и поднять ноги выше головы или сесть и опустить голову между колен. Ни в коем случае не пытайтесь идти или вести машину, если у вас кружится голова!&lt;br/&gt;
        ///• В течение 3–4 часов не снимайте повязку и старайтесь ее не мочить. Это убережет вас от воз [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string AfterBloodDonationDescription {
            get {
                return ResourceManager.GetString("AfterBloodDonationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анализ.
        /// </summary>
        public static string Analisis {
            get {
                return ResourceManager.GetString("Analisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О нас.
        /// </summary>
        public static string AskQuestion {
            get {
                return ResourceManager.GetString("AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перед кроводачей.
        /// </summary>
        public static string BeforeBloodGive {
            get {
                return ResourceManager.GetString("BeforeBloodGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сдача.
        /// </summary>
        public static string BeforeTime {
            get {
                return ResourceManager.GetString("BeforeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кровь сдается для.
        /// </summary>
        public static string BloodGivedFor {
            get {
                return ResourceManager.GetString("BloodGivedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробности.
        /// </summary>
        public static string BloodGiveMore {
            get {
                return ResourceManager.GetString("BloodGiveMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кроводача.
        /// </summary>
        public static string BloodGiveTitle {
            get {
                return ResourceManager.GetString("BloodGiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кроводача.
        /// </summary>
        public static string BloodGiveTitle2 {
            get {
                return ResourceManager.GetString("BloodGiveTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид кроводачи.
        /// </summary>
        public static string BloodGiveType {
            get {
                return ResourceManager.GetString("BloodGiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа крови.
        /// </summary>
        public static string BloodGroup {
            get {
                return ResourceManager.GetString("BloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станции переливания крови.
        /// </summary>
        public static string BloodStations {
            get {
                return ResourceManager.GetString("BloodStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Календарь.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удается выполнить вход. Убедитесь, что режим &quot;в самолете&quot; выключен и имеется сетевое соединение..
        /// </summary>
        public static string CantEnterCheckNetwork {
            get {
                return ResourceManager.GetString("CantEnterCheckNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий:.
        /// </summary>
        public static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий.
        /// </summary>
        public static string CommentLabelEdit {
            get {
                return ResourceManager.GetString("CommentLabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на противопоказания.
        /// </summary>
        public static string ContrasHeader {
            get {
                return ResourceManager.GetString("ContrasHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные отправлены.
        /// </summary>
        public static string DataSend {
            get {
                return ResourceManager.GetString("DataSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата и время.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключить геолокацию.
        /// </summary>
        public static string DisableGeolocation {
            get {
                return ResourceManager.GetString("DisableGeolocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://donorapp.ru/.
        /// </summary>
        public static string DonorappSite {
            get {
                return ResourceManager.GetString("DonorappSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помочь спасти жизнь.
        /// </summary>
        public static string donorfriendDescription {
            get {
                return ResourceManager.GetString("donorfriendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Друг донора.
        /// </summary>
        public static string donorfriendTitle {
            get {
                return ResourceManager.GetString("donorfriendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доноры.
        /// </summary>
        public static string Donors {
            get {
                return ResourceManager.GetString("Donors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доноры детям.
        /// </summary>
        public static string DonorsForChildren {
            get {
                return ResourceManager.GetString("DonorsForChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отсутствует.
        /// </summary>
        public static string DontExists {
            get {
                return ResourceManager.GetString("DontExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указано.
        /// </summary>
        public static string DontFilledData {
            get {
                return ResourceManager.GetString("DontFilledData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Еще не отмечено как выполненное.
        /// </summary>
        public static string DontFinished {
            get {
                return ResourceManager.GetString("DontFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не выбран.
        /// </summary>
        public static string DontSelected {
            get {
                return ResourceManager.GetString("DontSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не выбрано.
        /// </summary>
        public static string DontSelected2 {
            get {
                return ResourceManager.GetString("DontSelected2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы сегодня сдавали кровь?.
        /// </summary>
        public static string DoYouGiveBloodToday {
            get {
                return ResourceManager.GetString("DoYouGiveBloodToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail.
        /// </summary>
        public static string EmailHelp {
            get {
                return ResourceManager.GetString("EmailHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на empty.
        /// </summary>
        public static string EmptyType {
            get {
                return ResourceManager.GetString("EmptyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить геолокацию.
        /// </summary>
        public static string EnableGeolocation {
            get {
                return ResourceManager.GetString("EnableGeolocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите e-mail.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если у вас нет аккаунта, введите пароль и e-mail для начала регистрации..
        /// </summary>
        public static string EnterLoginAndPasswordToRegister {
            get {
                return ResourceManager.GetString("EnterLoginAndPasswordToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста войдите, чтобы иметь возможность работать с календарем событий..
        /// </summary>
        public static string EnterToWorkWithCalendar {
            get {
                return ResourceManager.GetString("EnterToWorkWithCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ваш e-mail.
        /// </summary>
        public static string EnterYourEmailForRestorePassword {
            get {
                return ResourceManager.GetString("EnterYourEmailForRestorePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cобытие.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип события.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязать профиль Facebook.
        /// </summary>
        public static string FacebookLinking {
            get {
                return ResourceManager.GetString("FacebookLinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход через Facebook.
        /// </summary>
        public static string FacebookLogin {
            get {
                return ResourceManager.GetString("FacebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь с Facebook разорвана.
        /// </summary>
        public static string FacebookUnlinkedMessage {
            get {
                return ResourceManager.GetString("FacebookUnlinkedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязан профиль Facebook.
        /// </summary>
        public static string FacebookUnLinking {
            get {
                return ResourceManager.GetString("FacebookUnLinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женский.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнено.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на O(I).
        /// </summary>
        public static string FirrstBloodGroup {
            get {
                return ResourceManager.GetString("FirrstBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сдал кровь первый раз.
        /// </summary>
        public static string first_bloodDescription {
            get {
                return ResourceManager.GetString("first_bloodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первая сдача крови.
        /// </summary>
        public static string first_bloodTitle {
            get {
                return ResourceManager.GetString("first_bloodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на O(I).
        /// </summary>
        public static string FirstBloodGroup {
            get {
                return ResourceManager.GetString("FirstBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на для доноров.
        /// </summary>
        public static string ForDonorsStation {
            get {
                return ResourceManager.GetString("ForDonorsStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AB(IV).
        /// </summary>
        public static string ForthBloodGroup {
            get {
                return ResourceManager.GetString("ForthBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (звонок из регионов бесплатный).
        /// </summary>
        public static string FreeCallFromRegions {
            get {
                return ResourceManager.GetString("FreeCallFromRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пт.
        /// </summary>
        public static string FridayShort {
            get {
                return ResourceManager.GetString("FridayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записано кроводач.
        /// </summary>
        public static string GivedBloodCount {
            get {
                return ResourceManager.GetString("GivedBloodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гранулоциты.
        /// </summary>
        public static string Granulocytes {
            get {
                return ResourceManager.GetString("Granulocytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Не приходите сдавать кровь, если вы чувствуете недомогание (озноб, головокружение, головную боль, слабость).&lt;br/&gt;
        ///                                    • Не курите за час до донации.&lt;br/&gt;
        ///                                    • Не принимайте алкоголь за 48 часов до донации.&lt;br/&gt;
        ///                                    • Обязательно выспитесь и съешьте легкий завтрак (сладкий чай, сухое печенье, каша на воде).&lt;br/&gt;
        ///                                    • Старайтесь ограничить прием жирной и жареной пищи накануне [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string HelpRecomendations {
            get {
                return ResourceManager.GetString("HelpRecomendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на памятка.
        /// </summary>
        public static string HelpRules {
            get {
                return ResourceManager.GetString("HelpRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Праздник.
        /// </summary>
        public static string HolidayType {
            get {
                return ResourceManager.GetString("HolidayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на info@donors.ru.
        /// </summary>
        public static string InfoDonorsEmail {
            get {
                return ResourceManager.GetString("InfoDonorsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Itsbeta.
        /// </summary>
        public static string Itsbeta {
            get {
                return ResourceManager.GetString("Itsbeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Узнать результат.
        /// </summary>
        public static string KnowResult {
            get {
                return ResourceManager.GetString("KnowResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на основное.
        /// </summary>
        public static string MainStationPivot {
            get {
                return ResourceManager.GetString("MainStationPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мужской.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на карта.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция.
        /// </summary>
        public static string MapStation {
            get {
                return ResourceManager.GetString("MapStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пн.
        /// </summary>
        public static string MondayShort {
            get {
                return ResourceManager.GetString("MondayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Москва.
        /// </summary>
        public static string Moscow {
            get {
                return ResourceManager.GetString("Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои значки.
        /// </summary>
        public static string MyBadges {
            get {
                return ResourceManager.GetString("MyBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуется регистрация в Москве или Московской области.
        /// </summary>
        public static string NeedRegistrationInMoscow {
            get {
                return ResourceManager.GetString("NeedRegistrationInMoscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующая кроводача.
        /// </summary>
        public static string NextBloodGive {
            get {
                return ResourceManager.GetString("NextBloodGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данных нет..
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет событий.
        /// </summary>
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станций не найдено. Измените параметры фильтра..
        /// </summary>
        public static string NoStations {
            get {
                return ResourceManager.GetString("NoStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прошло мало времени с последней кроводачи. .
        /// </summary>
        public static string NotTooMuchDaysFromLastBloodGive {
            get {
                return ResourceManager.GetString("NotTooMuchDaysFromLastBloodGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На карте.
        /// </summary>
        public static string OnMap {
            get {
                return ResourceManager.GetString("OnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запланировано: .
        /// </summary>
        public static string PlanedBloodGive {
            get {
                return ResourceManager.GetString("PlanedBloodGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планы.
        /// </summary>
        public static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плазма.
        /// </summary>
        public static string Plasma {
            get {
                return ResourceManager.GetString("Plasma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тромбоциты.
        /// </summary>
        public static string Platelets {
            get {
                return ResourceManager.GetString("Platelets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://podari-zhizn.ru.
        /// </summary>
        public static string PodariZhizn {
            get {
                return ResourceManager.GetString("PodariZhizn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Можно сдавать: .
        /// </summary>
        public static string PossibleBloodGive {
            get {
                return ResourceManager.GetString("PossibleBloodGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - возможная сдача.
        /// </summary>
        public static string PossibleBloodGiveTitle {
            get {
                return ResourceManager.GetString("PossibleBloodGiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  можно сдавать с .
        /// </summary>
        public static string PossibleGiveBloodStartingFrom {
            get {
                return ResourceManager.GetString("PossibleGiveBloodStartingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Политика конфиденциальности.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p&gt;Donor application PRIVACY POLICY&lt;/p&gt;
        ///&lt;p&gt;This application is owned and operated by Hintsolutions. Your privacy on the Internet is of the utmost importance to us. At Donor application, we want to make your experience online satisfying and safe.&lt;br&gt;
        ///Because we gather certain types of information about our users, we feel you should fully understand our policy and the terms and conditions surrounding the capture and use of that information. This privacy statement discloses what information we gather and how [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string PrivacyPolicyDescription {
            get {
                return ResourceManager.GetString("PrivacyPolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на профиль.
        /// </summary>
        public static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценить приложение.
        /// </summary>
        public static string RateAppButton {
            get {
                return ResourceManager.GetString("RateAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Читать дальше.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для активации достижения сделайте скан QR кода с наклейки к донорской справке. &lt;a href=&quot;http://www.blood.ru&quot;&gt;Подробнее о достижениях&lt;/a&gt;.
        ///Функционал дотижений доступен только в СПК ГНЦ РАМН. (http://www.blood.ru).
        /// </summary>
        public static string ReadQRAboutText {
            get {
                return ResourceManager.GetString("ReadQRAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Считать QR код.
        /// </summary>
        public static string ReadQrCode {
            get {
                return ResourceManager.GetString("ReadQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время приема.
        /// </summary>
        public static string RecepientTime {
            get {
                return ResourceManager.GetString("RecepientTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на рекомендации.
        /// </summary>
        public static string Recomendations {
            get {
                return ResourceManager.GetString("Recomendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прием региональной прописки.
        /// </summary>
        public static string RegionalCheck {
            get {
                return ResourceManager.GetString("RegionalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напоминание за:.
        /// </summary>
        public static string RememberBefore {
            get {
                return ResourceManager.GetString("RememberBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напоминание.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 15 минут.
        /// </summary>
        public static string Reminder15Minutes {
            get {
                return ResourceManager.GetString("Reminder15Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 день.
        /// </summary>
        public static string Reminder1Day {
            get {
                return ResourceManager.GetString("Reminder1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 час.
        /// </summary>
        public static string Reminder1Hour {
            get {
                return ResourceManager.GetString("Reminder1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 неделя.
        /// </summary>
        public static string Reminder1Week {
            get {
                return ResourceManager.GetString("Reminder1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2 дня.
        /// </summary>
        public static string Reminder2Days {
            get {
                return ResourceManager.GetString("Reminder2Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напомнить за.
        /// </summary>
        public static string ReminderBeforeEdit {
            get {
                return ResourceManager.GetString("ReminderBeforeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с указанной почтой не зарегистрирован.
        /// </summary>
        public static string RestoreEmailProblem {
            get {
                return ResourceManager.GetString("RestoreEmailProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На указанный e-mail отправлено письмо с инструкцией по востановлению доступа к учетной записи..
        /// </summary>
        public static string RestoreEmailSend {
            get {
                return ResourceManager.GetString("RestoreEmailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановить пароль.
        /// </summary>
        public static string RestorePassoword {
            get {
                return ResourceManager.GetString("RestorePassoword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Востановление пароля.
        /// </summary>
        public static string RestorePassword {
            get {
                return ResourceManager.GetString("RestorePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резус-фактор.
        /// </summary>
        public static string RhFactor {
            get {
                return ResourceManager.GetString("RhFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сб.
        /// </summary>
        public static string SaturdayShort {
            get {
                return ResourceManager.GetString("SaturdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работаем по субботам.
        /// </summary>
        public static string SaturdayWork {
            get {
                return ResourceManager.GetString("SaturdayWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сдал кровь второй раз.
        /// </summary>
        public static string secondbloodDescription {
            get {
                return ResourceManager.GetString("secondbloodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A(II).
        /// </summary>
        public static string SecondBloodGroup {
            get {
                return ResourceManager.GetString("SecondBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Два подряд.
        /// </summary>
        public static string secondbloodTitle {
            get {
                return ResourceManager.GetString("secondbloodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите дату.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УКАЖИТЕ ДАТУ.
        /// </summary>
        public static string SelectDatePopup {
            get {
                return ResourceManager.GetString("SelectDatePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УКАЖИТЕ ВРЕМЯ.
        /// </summary>
        public static string SelectTimePopup {
            get {
                return ResourceManager.GetString("SelectTimePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поделиться.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сайт.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скоро.
        /// </summary>
        public static string Soon {
            get {
                return ResourceManager.GetString("Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        public static string StationAddress {
            get {
                return ResourceManager.GetString("StationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на объявления.
        /// </summary>
        public static string StationAds {
            get {
                return ResourceManager.GetString("StationAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководитель.
        /// </summary>
        public static string StationChief {
            get {
                return ResourceManager.GetString("StationChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Район.
        /// </summary>
        public static string StationDistrict {
            get {
                return ResourceManager.GetString("StationDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта.
        /// </summary>
        public static string StationEmail {
            get {
                return ResourceManager.GetString("StationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр станций.
        /// </summary>
        public static string StationFilter {
            get {
                return ResourceManager.GetString("StationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регион.
        /// </summary>
        public static string StationRegion {
            get {
                return ResourceManager.GetString("StationRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отзывы.
        /// </summary>
        public static string StationReviews {
            get {
                return ResourceManager.GetString("StationReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станции.
        /// </summary>
        public static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск станции.
        /// </summary>
        public static string StationSearch {
            get {
                return ResourceManager.GetString("StationSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оставить отзыв.
        /// </summary>
        public static string StationWriteReview {
            get {
                return ResourceManager.GetString("StationWriteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Санкт-Петербург.
        /// </summary>
        public static string StPetersburg {
            get {
                return ResourceManager.GetString("StPetersburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить событие.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Было выполнено.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на противопоказания.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вс.
        /// </summary>
        public static string SundayShort {
            get {
                return ResourceManager.GetString("SundayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Временные противопоказания.
        /// </summary>
        public static string TempContras {
            get {
                return ResourceManager.GetString("TempContras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B(III).
        /// </summary>
        public static string ThirdBloodGroup {
            get {
                return ResourceManager.GetString("ThirdBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чт.
        /// </summary>
        public static string ThursdayShort {
            get {
                return ResourceManager.GetString("ThursdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проезд.
        /// </summary>
        public static string TransportStation {
            get {
                return ResourceManager.GetString("TransportStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вт.
        /// </summary>
        public static string TuesdayShort {
            get {
                return ResourceManager.GetString("TuesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указаны некорректные данные..
        /// </summary>
        public static string UncorrectLoginData {
            get {
                return ResourceManager.GetString("UncorrectLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не знаю.
        /// </summary>
        public static string UnknownBloodGroup {
            get {
                return ResourceManager.GetString("UnknownBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения.
        /// </summary>
        public static string UserBirthday {
            get {
                return ResourceManager.GetString("UserBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голосовать.
        /// </summary>
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буфет:.
        /// </summary>
        public static string vote_buffet {
            get {
                return ResourceManager.GetString("vote_buffet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лаборатория:.
        /// </summary>
        public static string vote_laboratory {
            get {
                return ResourceManager.GetString("vote_laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация кроводачи:.
        /// </summary>
        public static string vote_organization_donation {
            get {
                return ResourceManager.GetString("vote_organization_donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Врач-терапевт:.
        /// </summary>
        public static string vote_physician {
            get {
                return ResourceManager.GetString("vote_physician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистратура:.
        /// </summary>
        public static string vote_registry {
            get {
                return ResourceManager.GetString("vote_registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помещение:.
        /// </summary>
        public static string vote_room {
            get {
                return ResourceManager.GetString("vote_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на График работы:.
        /// </summary>
        public static string vote_schedule {
            get {
                return ResourceManager.GetString("vote_schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Было выполнено.
        /// </summary>
        public static string WasFinished {
            get {
                return ResourceManager.GetString("WasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ср.
        /// </summary>
        public static string WednesdayShort {
            get {
                return ResourceManager.GetString("WednesdayShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цельная кровь.
        /// </summary>
        public static string WholeBlood {
            get {
                return ResourceManager.GetString("WholeBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://yadonor.ru/.
        /// </summary>
        public static string YadonorSite {
            get {
                return ResourceManager.GetString("YadonorSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете сдать кровь, если:.
        /// </summary>
        public static string YouCanGiveBloodIf {
            get {
                return ResourceManager.GetString("YouCanGiveBloodIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • вы не употребляли алкоголь за последние 48 часов;&lt;br/&gt;
        ///• вы не принимали анальгетики за последние 72 часа;&lt;br/&gt;
        ///• для женщин: после окончания менструации прошло 5 дней;&lt;br/&gt;
        ///• вам не удаляли зуб за последние 10 дней;&lt;br/&gt;
        ///• вы не принимали антибиотики за последние 2 недели;&lt;br/&gt;
        ///• вы не болели ангиной, гриппом, ОРВИ за последний месяц;&lt;br/&gt;
        ///• у вас не было обострения аллергии за последние 2 месяца.&lt;br/&gt;.
        /// </summary>
        public static string YouCanGiveBloodIfDescription {
            get {
                return ResourceManager.GetString("YouCanGiveBloodIfDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете запланировать кроводачу: .
        /// </summary>
        public static string YouCanPlanBlood {
            get {
                return ResourceManager.GetString("YouCanPlanBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете запланировать кроводачу.
        /// </summary>
        public static string YouCanPlanBlood2 {
            get {
                return ResourceManager.GetString("YouCanPlanBlood2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В данный день вы еще не можете производить сдачу крови..
        /// </summary>
        public static string YouCantPlanBloodGiveThisDay {
            get {
                return ResourceManager.GetString("YouCantPlanBloodGiveThisDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы сдали: .
        /// </summary>
        public static string YouGiveBlood {
            get {
                return ResourceManager.GetString("YouGiveBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы сдали кровь. Спасибо! Рассчитан интервал до следующей возможной кроводачи.
        /// </summary>
        public static string YouGiveBloodThanks {
            get {
                return ResourceManager.GetString("YouGiveBloodThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завтра у вас запланирована кроводача..
        /// </summary>
        public static string YouHaveBloodGiveTomorrow {
            get {
                return ResourceManager.GetString("YouHaveBloodGiveTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На этот день у вас уже запланировано событие.
        /// </summary>
        public static string YouHaveEventAtThisDay {
            get {
                return ResourceManager.GetString("YouHaveEventAtThisDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше имя.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша оценка.
        /// </summary>
        public static string YourRate {
            get {
                return ResourceManager.GetString("YourRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш отзыв.
        /// </summary>
        public static string YourReviewDescription {
            get {
                return ResourceManager.GetString("YourReviewDescription", resourceCulture);
            }
        }
    }
}
