//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Donor.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абсолютные противопоказания.
        /// </summary>
        public static string AbsContras {
            get {
                return ResourceManager.GetString("AbsContras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to аккаунт.
        /// </summary>
        public static string AccountHeader {
            get {
                return ResourceManager.GetString("AccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запланировать.
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить отзыв.
        /// </summary>
        public static string AddReview {
            get {
                return ResourceManager.GetString("AddReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объявления.
        /// </summary>
        public static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объявления.
        /// </summary>
        public static string AdsTitle {
            get {
                return ResourceManager.GetString("AdsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ.
        /// </summary>
        public static string Analisis {
            get {
                return ResourceManager.GetString("Analisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to задать вопрос.
        /// </summary>
        public static string AskQuestion {
            get {
                return ResourceManager.GetString("AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перед кроводачей.
        /// </summary>
        public static string BeforeBloodGive {
            get {
                return ResourceManager.GetString("BeforeBloodGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сдача.
        /// </summary>
        public static string BeforeTime {
            get {
                return ResourceManager.GetString("BeforeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кровь сдается для.
        /// </summary>
        public static string BloodGivedFor {
            get {
                return ResourceManager.GetString("BloodGivedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности.
        /// </summary>
        public static string BloodGiveMore {
            get {
                return ResourceManager.GetString("BloodGiveMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кроводача.
        /// </summary>
        public static string BloodGiveTitle {
            get {
                return ResourceManager.GetString("BloodGiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид кроводачи.
        /// </summary>
        public static string BloodGiveType {
            get {
                return ResourceManager.GetString("BloodGiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа крови.
        /// </summary>
        public static string BloodGroup {
            get {
                return ResourceManager.GetString("BloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станции переливания крови.
        /// </summary>
        public static string BloodStations {
            get {
                return ResourceManager.GetString("BloodStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Календарь.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается выполнить вход. Убедитесь, что режим &quot;в самолете&quot; выключен и имеется сетевое соединение..
        /// </summary>
        public static string CantEnterCheckNetwork {
            get {
                return ResourceManager.GetString("CantEnterCheckNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий:.
        /// </summary>
        public static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string CommentLabelEdit {
            get {
                return ResourceManager.GetString("CommentLabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to противопоказания.
        /// </summary>
        public static string ContrasHeader {
            get {
                return ResourceManager.GetString("ContrasHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные отправлены.
        /// </summary>
        public static string DataSend {
            get {
                return ResourceManager.GetString("DataSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доноры.
        /// </summary>
        public static string Donors {
            get {
                return ResourceManager.GetString("Donors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доноры детям.
        /// </summary>
        public static string DonorsForChildren {
            get {
                return ResourceManager.GetString("DonorsForChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще не отмечено как выполненное.
        /// </summary>
        public static string DontFinished {
            get {
                return ResourceManager.GetString("DontFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы сегодня сдавали кровь?.
        /// </summary>
        public static string DoYouGiveBloodToday {
            get {
                return ResourceManager.GetString("DoYouGiveBloodToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EmailHelp {
            get {
                return ResourceManager.GetString("EmailHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string EmptyType {
            get {
                return ResourceManager.GetString("EmptyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите e-mail.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если у вас нет аккаунта, введите пароль и e-mail для начала регистрации..
        /// </summary>
        public static string EnterLoginAndPasswordToRegister {
            get {
                return ResourceManager.GetString("EnterLoginAndPasswordToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста войдите, чтобы иметь возможность работать с календарем событий..
        /// </summary>
        public static string EnterToWorkWithCalendar {
            get {
                return ResourceManager.GetString("EnterToWorkWithCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cобытие.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип события.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь с Facebook разорвана.
        /// </summary>
        public static string FacebookUnlinkedMessage {
            get {
                return ResourceManager.GetString("FacebookUnlinkedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женский.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнено.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(I).
        /// </summary>
        public static string FirstBloodGroup {
            get {
                return ResourceManager.GetString("FirstBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to для доноров.
        /// </summary>
        public static string ForDonorsStation {
            get {
                return ResourceManager.GetString("ForDonorsStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB(IV).
        /// </summary>
        public static string ForthBloodGroup {
            get {
                return ResourceManager.GetString("ForthBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записано кроводач.
        /// </summary>
        public static string GivedBloodCount {
            get {
                return ResourceManager.GetString("GivedBloodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to памятка.
        /// </summary>
        public static string HelpRules {
            get {
                return ResourceManager.GetString("HelpRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@donors.ru.
        /// </summary>
        public static string InfoDonorsEmail {
            get {
                return ResourceManager.GetString("InfoDonorsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать результат.
        /// </summary>
        public static string KnowResult {
            get {
                return ResourceManager.GetString("KnowResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to основное.
        /// </summary>
        public static string MainStationPivot {
            get {
                return ResourceManager.GetString("MainStationPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужской.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to карта.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станция.
        /// </summary>
        public static string MapStation {
            get {
                return ResourceManager.GetString("MapStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Москва.
        /// </summary>
        public static string Moscow {
            get {
                return ResourceManager.GetString("Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующая кроводача.
        /// </summary>
        public static string NextBloodGive {
            get {
                return ResourceManager.GetString("NextBloodGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет событий.
        /// </summary>
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станций не найдено. Измените параметры фильтра..
        /// </summary>
        public static string NoStations {
            get {
                return ResourceManager.GetString("NoStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На карте.
        /// </summary>
        public static string OnMap {
            get {
                return ResourceManager.GetString("OnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запланировано: .
        /// </summary>
        public static string PlanedBloodGive {
            get {
                return ResourceManager.GetString("PlanedBloodGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планы.
        /// </summary>
        public static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://podari-zhizn.ru.
        /// </summary>
        public static string PodariZhizn {
            get {
                return ResourceManager.GetString("PodariZhizn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можно сдавать: .
        /// </summary>
        public static string PossibleBloodGive {
            get {
                return ResourceManager.GetString("PossibleBloodGive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to профиль.
        /// </summary>
        public static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Считать QR код.
        /// </summary>
        public static string ReadQrCode {
            get {
                return ResourceManager.GetString("ReadQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время приема.
        /// </summary>
        public static string RecepientTime {
            get {
                return ResourceManager.GetString("RecepientTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рекомендации.
        /// </summary>
        public static string Recomendations {
            get {
                return ResourceManager.GetString("Recomendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прием региональной прописки.
        /// </summary>
        public static string RegionalCheck {
            get {
                return ResourceManager.GetString("RegionalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напоминание за:.
        /// </summary>
        public static string RememberBefore {
            get {
                return ResourceManager.GetString("RememberBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напоминание.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 минут.
        /// </summary>
        public static string Reminder15Minutes {
            get {
                return ResourceManager.GetString("Reminder15Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 день.
        /// </summary>
        public static string Reminder1Day {
            get {
                return ResourceManager.GetString("Reminder1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 час.
        /// </summary>
        public static string Reminder1Hour {
            get {
                return ResourceManager.GetString("Reminder1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 неделя.
        /// </summary>
        public static string Reminder1Week {
            get {
                return ResourceManager.GetString("Reminder1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 дня.
        /// </summary>
        public static string Reminder2Days {
            get {
                return ResourceManager.GetString("Reminder2Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напомнить за.
        /// </summary>
        public static string ReminderBeforeEdit {
            get {
                return ResourceManager.GetString("ReminderBeforeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить пароль.
        /// </summary>
        public static string RestorePassoword {
            get {
                return ResourceManager.GetString("RestorePassoword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резус-фактор.
        /// </summary>
        public static string RhFactor {
            get {
                return ResourceManager.GetString("RhFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работаем по субботам.
        /// </summary>
        public static string SaturdayWork {
            get {
                return ResourceManager.GetString("SaturdayWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(II).
        /// </summary>
        public static string SecondBloodGroup {
            get {
                return ResourceManager.GetString("SecondBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to объявления.
        /// </summary>
        public static string StationAds {
            get {
                return ResourceManager.GetString("StationAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отзывы.
        /// </summary>
        public static string StationReviews {
            get {
                return ResourceManager.GetString("StationReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станции.
        /// </summary>
        public static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск станции.
        /// </summary>
        public static string StationSearch {
            get {
                return ResourceManager.GetString("StationSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставить отзыв.
        /// </summary>
        public static string StationWriteReview {
            get {
                return ResourceManager.GetString("StationWriteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Санкт-Петербург.
        /// </summary>
        public static string StPetersburg {
            get {
                return ResourceManager.GetString("StPetersburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить событие.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Было выполнено.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to противопоказания.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Временные противопоказания.
        /// </summary>
        public static string TempContras {
            get {
                return ResourceManager.GetString("TempContras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B(III).
        /// </summary>
        public static string ThirdBloodGroup {
            get {
                return ResourceManager.GetString("ThirdBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проезд.
        /// </summary>
        public static string TransportStation {
            get {
                return ResourceManager.GetString("TransportStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указаны некорректные данные..
        /// </summary>
        public static string UncorrectLoginData {
            get {
                return ResourceManager.GetString("UncorrectLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голосовать.
        /// </summary>
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Буфет:.
        /// </summary>
        public static string vote_buffet {
            get {
                return ResourceManager.GetString("vote_buffet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лаборатория:.
        /// </summary>
        public static string vote_laboratory {
            get {
                return ResourceManager.GetString("vote_laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация кроводачи:.
        /// </summary>
        public static string vote_organization_donation {
            get {
                return ResourceManager.GetString("vote_organization_donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Врач-терапевт:.
        /// </summary>
        public static string vote_physician {
            get {
                return ResourceManager.GetString("vote_physician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистратура:.
        /// </summary>
        public static string vote_registry {
            get {
                return ResourceManager.GetString("vote_registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помещение:.
        /// </summary>
        public static string vote_room {
            get {
                return ResourceManager.GetString("vote_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График работы:.
        /// </summary>
        public static string vote_schedule {
            get {
                return ResourceManager.GetString("vote_schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Было выполнено.
        /// </summary>
        public static string WasFinished {
            get {
                return ResourceManager.GetString("WasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете сдать кровь, если:.
        /// </summary>
        public static string YouCanGiveBloodIf {
            get {
                return ResourceManager.GetString("YouCanGiveBloodIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы сдали: .
        /// </summary>
        public static string YouGiveBlood {
            get {
                return ResourceManager.GetString("YouGiveBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завтра у вас запланирована кроводача..
        /// </summary>
        public static string YouHaveBloodGiveTomorrow {
            get {
                return ResourceManager.GetString("YouHaveBloodGiveTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше имя.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
